CREATE PROC EmployeeCreatOrUpdate
@EMP_ID varchar(50), 
@EMP_FNAME varchar(50), 
@EMP_LNAME varchar(50), 
@EMP_DOB date, 
@EMP_EMAIL varchar(50), 
@EMP_PASS varchar(50), 
@EMP_PHONE varchar(50), 
@EMP_ADDRESS varchar(50)
AS

BEGIN
IF (@EMP_ID = null)

BEGIN
	INSERT INTO Employee([EMP_FNAME], [EMP_LNAME], [EMP_DOB], [EMP_EMAIL], [EMP_PASS], [EMP_PHONE], [EMP_ADDRESS])
	VALUES(@EMP_FNAME, @EMP_LNAME,@EMP_DOB, @EMP_EMAIL, @EMP_PASS, @EMP_PHONE, @EMP_ADDRESS)
END

ELSE

BEGIN

UPDATE Employee
SET
EMP_FNAME = @EMP_FNAME,
EMP_LNAME = @EMP_LNAME,
EMP_DOB = @EMP_DOB,
EMP_EMAIL = @EMP_EMAIL,
EMP_PASS = @EMP_PASS,
EMP_PHONE = @EMP_PHONE,
EMP_ADDRESS = @EMP_ADDRESS

END
END